services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6336:6336"
    env_file: .env
    volumes:
      - ./.configs/.khorcha-pati-docker.yaml:/app/.configs/.khorcha-pati.yaml
      - sqlite-data:/app/.sqlite
    restart: unless-stopped

  frontend:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./web/config.json:/app/config.json:ro
    restart: unless-stopped

volumes:
  sqlite-data:
